---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travels
  namespace: travel-portal
spec:
  selector:
    matchLabels:
      app: travels
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: travels
        version: v1
    spec:
      containers:
        - name: control
          image: quay.io/kiali/demo_travels_portal:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          securityContext:
            privileged: false
          env:
            - name: LISTEN_ADDRESS
              value: ':8000'
            - name: PORTAL_COORDINATES
              value: '55.956245,-3.187915'
            - name: PORTAL_COUNTRY
              value: 'United Kingdom'
            - name: PORTAL_NAME
              value: 'travels.uk'
            - name: TRAVELS_AGENCY_SERVICE
              value: 'http://travels-vm.travel-agency:8000'
---
apiVersion: v1
kind: Service
metadata:
  name: travels
  namespace: travel-portal
  labels:
    app: travels
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: travels
