---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ossm-checker
  namespace: travel-control
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ossm-checker
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ossm-checker
  namespace: travel-control
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ossm-checker
  namespace: travel-control
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
data:
  playbook.yaml: |
    ---
    - name: ossm status checker
      hosts: localhost
      connection: local
      gather_facts: false
      tasks:
        - name: check ossm smcp status
          kubernetes.core.k8s_info:
            api_version: maistra.io/v2
            kind: ServiceMeshControlPlane
            name: "basic"
            namespace: "istio-system"
          register: r_smcp
          retries: "30"
          delay: "5"
          until:
          - r_smcp is defined
          - r_smcp.resources is defined
          - r_smcp.resources | length > 0
          - r_smcp.resources[0].status is defined
          - r_smcp.resources[0].status.readiness is defined
          - r_smcp.resources[0].status.readiness.components is defined
          - r_smcp.resources[0].status.readiness.components.ready is defined
          - r_smcp.resources[0].status.readiness.components.ready | length == 8
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ossm-checker
  namespace: travel-control
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: Never
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: ossm-checker
      restartPolicy: Never
      containers:
      - name: ansible
        image: quay.io/agnosticd/ee-multicloud:2025-04-14
        command: ["ansible-playbook"]
        args: ["/ansible/playbook.yaml"]
        volumeMounts:
        - name: ansible
          mountPath: /ansible
      volumes:
      - name: ansible
        configMap:
          name: ossm-checker
