---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: control-gateway
  namespace: istio-system
  labels:
    module: m3
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  servers:
    - hosts:
        - $ISTIO_INGRESS_ROUTE_URL
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway"|oc -n istio-system apply -f -
