kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control
  namespace: travel-control
  labels:
    module: m5
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hosts:
    - "istio-ingressgateway-istio-system.{{ .Values.domain }}"
  gateways:
    - istio-system/control-gateway
  http:
    - route:
        - destination:
            host: control-vm.travel-control.svc.cluster.local
            subset: v1
          weight: 100